### ISSUE TITLE
Metaphone encoding of 'W' and 'WH' is ''

### ISSUE THREAD

**Issue by ahood** [chrislit/abydos#169]
Looking for justification of this since 'W' is **explicitly** chosen as the encoding in two other implementations, https://github.com/howardjp/phonics and https://github.com/jamesturk/jellyfish, as evidenced in https://github.com/cran/phonics/blob/master/src/metaphone.cpp and https://github.com/jamesturk/jellyfish-testdata/blob/4a2093f1ebce657e8300b3f4404707edf65c9685/metaphone.csv, respectively. In fact, in the former the author states more generally that the metaphone encoding of a single letter should be itself.

Based on the brief discussion of NYSIIS we had I don't doubt that the choice of encoding 'W' and 'WH' as '' is based on good reasons, presumably in this case the reference implementation or another source. Can you please confirm that you are satisfied that '' should be the encoding for 'WH' and 'W' and point me to where I can find the justification?

**Comment by chrislit** [comment]
The reference implementation of Metaphone can be found at http://aspell.net/metaphone/metaphone.basic. It converts initial 'WH' to 'W' around line 18. Then in the third to the last case, drops all cases of 'W' and 'Y' that are not followed by a vowel. The two C implementations at that page also have this behavior.
I checked Double Metaphone & Metaphone 3, and they both have quite similar behavior. In both cases, 'WH' becomes 'A', '' and 'W' becomes '', ''. I may try to get ahold of Philips' original article describing Metaphone to see if there's any more info there.
I don't think it's a bad idea to map 'W' to 'W', as in phonics & jellyfish, but it's not faithful to the original implementation. I may add a Metaphone variant that incorporates the changes made in Apache Commons' Codec implementation, as they've noticed a number of these types of 'bugs' in the original (see https://issues.apache.org/jira/browse/CODEC-57). I think Philips' original intention was to keep W & Y when they are consonants and discard them when they're vowels, so keeping 'W' when it is the complete string makes sense.
