### ISSUE TITLE
Does it have Metaphone 3? 

### ISSUE THREAD

**Issue by jcopps** [chrislit/abydos#230]
Does it have Metaphone 3?

**Comment by chrislit** [comment]
No. Unfortunately, although Metaphone 3 2.1.3 was released under the BSD 3-clause license as part of Google Refine, which became OpenRefine (https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/clustering/binning/Metaphone3.java), the author, Lawrence Philips, doesn't want that code used for ports to other languages or used in any way outside of OpenRefine. In accordance with his wishes, to my knowledge, no one has released Metaphone 3 ports to other languages or included it other libraries.

His comments discussing the licensing can be found here:
- https://github.com/threedaymonk/text/issues/21#issuecomment-67752327
- https://news.ycombinator.com/item?id=8779517

To be clear, Philips released his code under BSD 3-clause and acknowledges this. He apparently had no clue what this entailed and has no legal right to retract the BSD licensing. But everyone has acceded to his wishes that his code not be ported to other languages out of courtesy.

**Comment by doublex** [comment]
Interesting, nobody ported Metaphone3 to Python. 
Only ported to `go`:
https://github.com/snadrus/metaphone3/blob/main/metaphone3.go
