### ISSUE TITLE
Bag distance calculation

### ISSUE THREAD

**Issue by Yomguithereal** [chrislit/abydos#48]
Hello @chrislit,

First of all, I wanted to thank you for your tremendous work on this library. I have started not long ago a somewhat similar library for JavaScript called [Talisman](https://github.com/Yomguithereal/talisman) and stumbled upon your very well documented code quite early.

However, I started implementing the "bag" distance and the only article I found on this subject was this one: http://www-db.disi.unibo.it/research/papers/SPIRE02.pdf

> "String Matching with Metric Trees Using an Approximate Distance." Ilaria Bartolini, Paolo Ciaccia, and Marco Patella.

So I was wondering whether you had the same source because I may have found a mistake in your implementation.

In this [line](https://github.com/chrislit/abydos/blob/master/abydos/distance.py#L2423), your return the max of the differences using the python `len` function, which, on a `Counter` returns the number of distinct values in the set rather than the total number of items remaining. The article, or this how I understand it, seems to indicate we need to work on the total number of items in the difference, not the number of distinct items. This would be `len(set.elements())` rather than `len(set)`.

What do you think?

**Comment by orsinium** [comment]
Instead of `len(src.elements())` you can use `sum(src.values())` as in [other functions](https://github.com/chrislit/abydos/blob/master/abydos/distance.py#L602) of this module.

**Comment by chrislit** [comment]
Thanks for catching this. You're absolutely correct, and I've applied @orsinium's suggested fix. I'm not sure how I missed this report for a year and a half, but it's finally corrected now.
